name: susma
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  auto_route: ^9.3.0+1
  shadcn_ui: ^0.17.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
